name: githubreleasePipeline
resources:
  repository: self
pool:
  name: 'Hosted Ubuntu 1604'
  demands: maven
stages:
- stage: dev
  jobs:
  - job: MyJob
    displayName: Dev Job
    continueOnError: true
    steps:
    - script: echo My dev job
- stage: QA1
  dependsOn: dev
  jobs:
  - job: QAJob
    displayName: QA1
    continueOnError: true
    steps:
    - script: echo My QA1 job
- stage: QA2
  dependsOn: dev
  jobs:
  - job: MyJob
    displayName: QA2
    continueOnError: true
    steps:
    - script: echo My QA2 job
