stages:
- stage: dev
  jobs:
  - job: MyJob
    displayName: Dev Job
    continueOnError: true
    pool:
      vmImage: 'ubuntu-16.04'
      demand: maven
    steps:
    - task: Maven@3
      displayName: 'Maven pom.xml(lite)'
      inputs:
        mavenPomFile: 'pom-lite.xml'
