stages:
- stage: Dev
  jobs:
  - job: DevJob
    displayName: Dev
    continueOnError: true
    pool:
      vmImage: 'ubuntu-16.04'
      demand: maven
    steps:
    - task: Maven@3
      displayName: 'Maven pom.xml(lite)'
      inputs:
        mavenPomFile: 'pom-lite.xml'
    - task: Maven@3
      displayName: 'Maven pom.xml(full)'
      inputs:
        mavenPomFile: 'pom-full.xml'
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- stage: Test
  dependsOn: Dev
  jobs:
  - job: TestJob
    displayName: Test    
    pool:
      vmImage: 'ubuntu-16.04'
      demand: maven 
    steps:
    - script: |
        echo "running tests..."
        echo 'Tests complete.'

- stage: Staging
  dependsOn: Test
  jobs:
  - job: StagingJob   
    displayName: Staging 
    pool:
      vmImage: 'ubuntu-16.04'
      demand: maven 
    steps:
    - bash: |  
        echo "Starting to deploy to Staging..."
        echo "Deploy to staging complete..." 
      displayName: 'Deploy to staging'

    - task: GithubRelease@0 # github release task starts
      displayName: 'Create GitHub Release'
      inputs:
        githubConnection: zenithworks
        repositoryName: zenithworks/javaAppWithMaven
        


